server:
  port: 8001
spring:
  # DB 配置
  datasource:
    url: *****
    username: *****
    password: *****
  # 缓存配置
  redis:
    host: *****
    port: *****
    password: *****
  resources:
    # 不要为我们工程中的资源文件建立映射
    add-mappings: false
    static-locations: classpath:/resources/,classpath:/static/
  #session:
    # session存储方式采用redis
    #store-type: redis

mybatis:
  # 设置mybatis配置文件路径
  config-location: classpath:mybatis/mybatis-config.xml
  # 设置mybatis sql脚本文件路径
  mapper-locations: classpath*:mapper/*.xml
  # 设置mybatis实体类包路径
  type-aliases-package: com.aquaman.security.admin.entity.domain

# 定义日志级别
logging:
  level:
    com:
      aquaman:
        security:
          admin:
            mapper: debug

# Aquaman自定义配置项目
aquaman:
  security:
    authorization:
      login-page: /login
